export const LOAD_USERS = 'LOAD_USERS'

export const FILTERS_LOAD_QUERY = 'FILTERS_LOAD_QUERY'
export const FILTERS_LOAD_SCORE = 'FILTERS_LOAD_SCORE'
export const FILTERS_LOAD_ORDER_ASC = 'FILTERS_LOAD_ORDER_ASC'
export const FILTERS_LOAD_ORDER_TYPE = 'FILTERS_LOAD_ORDER_TYPE'
export const FILTERS_CLEAR = 'FILTERS_CLEAR'
